import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Shez App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Tangent</h1>

        <p className={styles.description}>
          Upload a receipt/bank statment etc and let us extract the important
          information out for you!
        </p>

        <div className={styles.uploadArea}>
          <div className={styles.uploadBox}>
            <p className={styles.uploadBoxText}>Drop image here</p>
          </div>
          <button className={styles.uploadButton}>Upload Image</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Tantrum
        </a>
      </footer>
    </div>
  );
}
